image: maven:3.3.9

pipelines:
  default:
    - step:
        caches:
          - maven 
        script:
            - mvn -B verify
  branches:
    master:
      - step:
          script:
            - mvn -B verify