server:
  applicationConnectors:
    - type: http
      port: 9090
      bindHost: 127.0.0.1 # only bind to loopback
      maxRequestHeaderSize: 8KiB
      maxResponseHeaderSize: 8KiB
      idleTimeout: 30 seconds
      minBufferPoolSize: 64 bytes
      bufferPoolIncrement: 1KiB
      maxBufferPoolSize: 64KiB
      acceptorThreads: 1
      selectorThreads: 2
      acceptQueueSize: 1024
      soLingerTime: 345s
      useServerHeader: false
      useDateHeader: true
      useForwardedHeaders: true
logging:
  level: DEBUG
  loggers:
    "io.dropwizard": DEBUG
  appenders:
    - type: console
metrics:
  reporters:
    - type: console
      timeZone: UTC
      output: stdout